version: "3.9"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: be-db
      MYSQL_USER: db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3309:3306"
    volumes:
      # - .docker/setupdb.sql:/docker-entrypoint-initdb.d/setupdb.sql
      - .docker/db-data:/var/lib/mysql